name: Unity CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Unity Project 🧱
    runs-on: ubuntu-latest

    steps:
      # Checkout del código fuente
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache para acelerar builds
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Assets/**', '**/Packages/**', '**/ProjectSettings/**') }}
          restore-keys: |
            Library-${{ runner.os }}

      # Compilar con Unity usando GameCI
      - name: Build with Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 6000.1.12f1
          targetPlatform: StandaloneWindows64  # O WebGL, Android, etc.

      # (Opcional) Subir los artefactos
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build/




